import type { Metadata } from "next";
import { Raleway, Open_Sans } from "next/font/google";

const raleway = Raleway({ variable: '--font-raleway', subsets: ["latin-ext"] });
const openSans = Open_Sans({variable: '--font-open-sans', subsets: ["latin-ext"]});

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="cs" className={`${raleway.variable} ${openSans.variable}`}>
      <body>{children}</body>
    </html>
  );
}
